### ISSUE TITLE
Why is there an offset

### ISSUE THREAD

**Issue by KonstSchob** [MohamedAshraf701/gradient-icon#4]
I love your tool, however this offset is annoying. I have to change it in the gradient_icons.dart, but of course when someone else gets my code they have to change it too. 
Can you make this option toggleable? Why is there an offset in the first place? I think your tool works best when just replacing an icon without any layout changes

![grafik](https://github.com/MohamedAshraf701/gradient-icon/assets/151203822/d24895d4-8f1f-4377-9d0a-2f22cf7b43e2)

**Comment by MohamedAshraf701** [comment]
Thank you for connecting we will fix this in new update or version 👍

**Comment by KonstSchob** [comment]
Thanks a lot
